### ISSUE TITLE
[BUG] Type Error

### ISSUE THREAD

**Issue by SiNiKin** [CheHyeonYeong/Do-tori#12]
## 어떤 버그인가요?

> 회원 가입 실행 시 회원 아이디 값이 데이터 베이스 PK 값으로 들어가려는 버그가 발생했습니다.
( uid 값이 id 값으로 들어가려고 함 / null값 발생 , 타입 오류 발생 )

## 어떤 상황에서 발생한 버그인가요?

> user entity, joindto 준비 후 회원가입 기능을 실행하려 했지만 값이 맞게 들어가지 않았습니다..

## 예상 결과

> 데이터 베이스 상 PK인 id는 자동으로 값이 입력되고 회원 아이디인 uid는 입력받은 값이 등록되어서 회원가입이 되는 좋은 결과.....

**Comment by CheHyeonYeong** [comment]
1. CustomSecurityConfig에서 람다식을 사용하지 않음!!! 모두가 빨간줄 좍좍임!!!!!! 이런 코드는 풀리퀘로 올리면 아니아니안돼요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2. public interface UserRepository extends JpaRepository<User, Long> 에서 map에 User - Pk의 타입으로 맞춰줘야 해요 ㅡㅅㅡ 스프링 부트 공부해오세용!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
3. 마지막으루 restful로 안되어 있어용!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
