### ISSUE TITLE
[BUG] Login Page 무한 리다이렉트

### ISSUE THREAD

**Issue by SiNiKin** [CheHyeonYeong/Do-tori#17]
## 어떤 버그인가요?

> 무한 리다이렉트 문제에 직면했습니다.

## 어떤 상황에서 발생한 버그인가요?

> 코드를 RESTful 방식으로 바꾼 뒤 서버를 실행하니 무한 리다이렉트에 직면했습니다. 쿠키를 삭제해도 안되고 시큐리티 config를 열심히 건들여봤지만 잘 안되더군요...

## 예상 결과

> 처음 보는 에러라 당황했지만 제 코드의 문제가 아주 많을 것 같습니다..

**Comment by CheHyeonYeong** [comment]
버그 이슈 제목 안달으셨어용

**Comment by CheHyeonYeong** [comment]
무한 리다이렉션이 혹시 어쩌다.. 걸리게 되나요? url중 어디를 들어간다거나.... 아니면 그냥 서버를 키면 바로 다운이 되나요?

**Comment by CheHyeonYeong** [comment]
> 해결 방안
Restful 방식으로 하기 앞서, Service, repository와 맞지 않은 메서드 사용 -> @SiNiKin 과 상의 이후, Restful 방식이 아닌 이전 방안으로 변경, 이에 따른 redirectiron등의 문제를 착안하여 에러 수정을 완료함!

```    

 Authentication authentication = SecurityContextHolder.getContext().getAuthentication();


   ```

해당 코드의 필요성을 느끼지 못해 대대적인 수정을 요함 -> @CheHyeonYeong 진행

> Date time
20240512 진행 완료에 맞춰 close 함
