### ISSUE TITLE
[BUG] 로그인/로그아웃 시 MY PAGE 메뉴 변경 안됨

### ISSUE THREAD

**Issue by Eunsu2002** [CheHyeonYeong/Do-tori#41]
## 어떤 버그인가요?

> 로그인 상태에 따라 메뉴가 변경 되지 않습니다

## 어떤 상황에서 발생한 버그인가요?

> auth logout 후

## 예상 결과

> login 때 MY PAGE, 로그아웃 이던 메뉴가 logout 시 로그인, 회원가입으로 변경.

## 참고할만한 자료(선택)
> https://devjun.tistory.com/269

**Comment by CheHyeonYeong** [comment]
캡쳐 화면도 첨부하면 짱이지롱

**Comment by CheHyeonYeong** [comment]
근데 지금 auth가 제대로 작동하지 않아서 logout 이후에도 logout이 제대로 안되는 에러가 있는 것 같아요! 은수님 문제가 아닐 수 있으니 내일 민준님과 함께할 때 이야기 해봅쉬당
