### ISSUE TITLE
[FEAT] MyPage 작업

### ISSUE THREAD

**Issue by Rencal3491** [CheHyeonYeong/Do-tori#5]
## 어떤 기능인가요? 

> MyPage 작업

## 작업 상세 내용

- [x] 회원 정보 수정
- [x] 회원 탈퇴
- [x] 로그인 / 로그아웃

**Comment by CheHyeonYeong** [comment]
회원 탈퇴 기능두 넣으래용

**Comment by CheHyeonYeong** [comment]
아가씨.. password너무 decoding 안되어서 올라가는거랑 아이디 비번 대충 아무 번호로 들어가도 괜찮은 부분 (Vaild 검사)가 빠져있어요 그 부분 진행해주세요!
